//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Text;
using BridalPOS.Model.Core.EntityClasses;

namespace BridalPOS.Model.Core
{
	/// <summary>Model builder class for code first development.</summary>
	public partial class LLBLGenProProject1ModelBuilder
	{
		/// <summary>Builds the model defined in this class with the modelbuilder specified. Called from the generated DbContext</summary>
		/// <param name="modelBuilder">The model builder to build the model with.</param>
		public virtual void BuildModel(DbModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema("dbo");
		}
	}
}

