//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BridalPOSEntities1 : DbContext
    {
        public BridalPOSEntities1()
            : base("name=BridalPOSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAction> tblActions { get; set; }
        public DbSet<tblCashDrawer> tblCashDrawers { get; set; }
        public DbSet<tblClass> tblClasses { get; set; }
        public DbSet<tblColor> tblColors { get; set; }
        public DbSet<tblColorNameList> tblColorNameLists { get; set; }
        public DbSet<tblColorNameListColor> tblColorNameListColors { get; set; }
        public DbSet<tblCommission> tblCommissions { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblEvent> tblEvents { get; set; }
        public DbSet<tblEventType> tblEventTypes { get; set; }
        public DbSet<tblFabric> tblFabrics { get; set; }
        public DbSet<tblFavorite> tblFavorites { get; set; }
        public DbSet<tblGeneralReport> tblGeneralReports { get; set; }
        public DbSet<tblInfoSource> tblInfoSources { get; set; }
        public DbSet<tblInventory> tblInventories { get; set; }
        public DbSet<tblItemStatu> tblItemStatus { get; set; }
        public DbSet<tblLeadTime> tblLeadTimes { get; set; }
        public DbSet<tblMember> tblMembers { get; set; }
        public DbSet<tblMemberRole> tblMemberRoles { get; set; }
        public DbSet<tblNeckLine> tblNeckLines { get; set; }
        public DbSet<tblNote> tblNotes { get; set; }
        public DbSet<tblPaymentType> tblPaymentTypes { get; set; }
        public DbSet<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public DbSet<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
        public DbSet<tblPurchaseStatu> tblPurchaseStatus { get; set; }
        public DbSet<tblReportMessage> tblReportMessages { get; set; }
        public DbSet<tblSchool> tblSchools { get; set; }
        public DbSet<tblSecurityLevel> tblSecurityLevels { get; set; }
        public DbSet<tblSilhouette> tblSilhouettes { get; set; }
        public DbSet<tblSizeRange> tblSizeRanges { get; set; }
        public DbSet<tblSleeve> tblSleeves { get; set; }
        public DbSet<tblStyleColor> tblStyleColors { get; set; }
        public DbSet<tblStyleColorNameList> tblStyleColorNameLists { get; set; }
        public DbSet<tblStyleFormat> tblStyleFormats { get; set; }
        public DbSet<tblStyleMaster> tblStyleMasters { get; set; }
        public DbSet<tblSysParameter> tblSysParameters { get; set; }
        public DbSet<tblTicket> tblTickets { get; set; }
        public DbSet<tblTicketDetail> tblTicketDetails { get; set; }
        public DbSet<tblTransactionType> tblTransactionTypes { get; set; }
        public DbSet<tblVendor> tblVendors { get; set; }
    }
}
