//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string Note { get; set; }
        public Nullable<short> ClerkId { get; set; }
        public int MemberId { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
