//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommission
    {
        public int Id { get; set; }
        public short EmployeeId { get; set; }
        public decimal Amount { get; set; }
        public bool IsPayable { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsActive { get; set; }
        public int TicketDetailId { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblTicketDetail tblTicketDetail { get; set; }
    }
}
