//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        public tblClass()
        {
            this.tblFavorites = new HashSet<tblFavorite>();
            this.tblLeadTimes = new HashSet<tblLeadTime>();
            this.tblStyleMasters = new HashSet<tblStyleMaster>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> MakeupPercent { get; set; }
        public Nullable<decimal> MakeupPrice { get; set; }
    
        public virtual ICollection<tblFavorite> tblFavorites { get; set; }
        public virtual ICollection<tblLeadTime> tblLeadTimes { get; set; }
        public virtual ICollection<tblStyleMaster> tblStyleMasters { get; set; }
    }
}
