//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblActions = new HashSet<tblAction>();
            this.tblCommissions = new HashSet<tblCommission>();
            this.tblEvents = new HashSet<tblEvent>();
            this.tblNotes = new HashSet<tblNote>();
        }
    
        public short Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<tblAction> tblActions { get; set; }
        public virtual ICollection<tblCommission> tblCommissions { get; set; }
        public virtual ICollection<tblEvent> tblEvents { get; set; }
        public virtual ICollection<tblNote> tblNotes { get; set; }
    }
}
