//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFavorite
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<short> ColorId { get; set; }
        public string Note { get; set; }
        public Nullable<short> ClassId { get; set; }
        public int MemberId { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblColor tblColor { get; set; }
        public virtual tblMember tblMember { get; set; }
        public virtual tblStyleMaster tblStyleMaster { get; set; }
    }
}
