//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory
    {
        public int Id { get; set; }
        public int StyleId { get; set; }
        public short ColorId { get; set; }
        public string Size { get; set; }
        public int Quantity { get; set; }
        public int SampleQty { get; set; }
        public int LayawayQty { get; set; }
        public Nullable<System.DateTime> DateOfSample { get; set; }
    
        public virtual tblColor tblColor { get; set; }
        public virtual tblStyleMaster tblStyleMaster { get; set; }
    }
}
