//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeadTime
    {
        public int Id { get; set; }
        public short VendorId { get; set; }
        public short ClassId { get; set; }
        public Nullable<short> RegLeadTime { get; set; }
        public Nullable<short> RushLeadTime { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
