//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public tblMember()
        {
            this.tblActions = new HashSet<tblAction>();
            this.tblEvents = new HashSet<tblEvent>();
            this.tblFavorites = new HashSet<tblFavorite>();
            this.tblMember1 = new HashSet<tblMember>();
            this.tblNotes = new HashSet<tblNote>();
            this.tblTickets = new HashSet<tblTicket>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Cell { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<short> SchoolId { get; set; }
        public Nullable<short> GradYear { get; set; }
        public Nullable<short> SourceInfoId { get; set; }
        public string Bust { get; set; }
        public string Waist { get; set; }
        public string Hip { get; set; }
        public string Size { get; set; }
        public string Height { get; set; }
        public Nullable<short> RoleId { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual ICollection<tblAction> tblActions { get; set; }
        public virtual ICollection<tblEvent> tblEvents { get; set; }
        public virtual ICollection<tblFavorite> tblFavorites { get; set; }
        public virtual tblInfoSource tblInfoSource { get; set; }
        public virtual ICollection<tblMember> tblMember1 { get; set; }
        public virtual tblMember tblMember2 { get; set; }
        public virtual tblMemberRole tblMemberRole { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual ICollection<tblNote> tblNotes { get; set; }
        public virtual ICollection<tblTicket> tblTickets { get; set; }
    }
}
