//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        public tblPurchaseOrder()
        {
            this.tblPurchaseOrderDetails = new HashSet<tblPurchaseOrderDetail>();
        }
    
        public int Id { get; set; }
        public short VendorId { get; set; }
        public string ShipVia { get; set; }
        public Nullable<System.DateTime> ReqShipDate { get; set; }
        public Nullable<System.DateTime> VendorShipDate { get; set; }
        public string VendorConf { get; set; }
        public string VendorSpokeTo { get; set; }
        public string Note { get; set; }
        public string RecPONote { get; set; }
        public System.DateTime PostedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public short StatusId { get; set; }
        public string VoidReason { get; set; }
        public string POName { get; set; }
    
        public virtual tblPurchaseStatu tblPurchaseStatu { get; set; }
        public virtual tblVendor tblVendor { get; set; }
        public virtual ICollection<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
    }
}
