//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderDetail
    {
        public int Id { get; set; }
        public int PurchaseOrderId { get; set; }
        public int TicketDetailId { get; set; }
        public short Line { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        public virtual tblTicketDetail tblTicketDetail { get; set; }
    }
}
