//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysParameter
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string TempOverridePwd { get; set; }
        public string OverridePwd { get; set; }
        public Nullable<double> DiscPercentPwd { get; set; }
        public Nullable<decimal> DiscPricePwd { get; set; }
        public Nullable<double> DepositPercent { get; set; }
        public Nullable<short> StyleFormatId { get; set; }
        public string ManagerPwd { get; set; }
        public string OwnerPwd { get; set; }
        public string TaxName1 { get; set; }
        public string TaxName2 { get; set; }
        public Nullable<double> TaxPercent1 { get; set; }
        public Nullable<double> TaxPercent2 { get; set; }
        public string ImagePath { get; set; }
        public int AutoStoreStyle { get; set; }
        public System.DateTime LastedRegisterSetup { get; set; }
        public string LogoPath { get; set; }
        public string CashRegisterStatus { get; set; }
        public Nullable<bool> BasePriceOnly { get; set; }
        public string TeamLeaderPwd { get; set; }
    
        public virtual tblStyleFormat tblStyleFormat { get; set; }
    }
}
