//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStyleMaster
    {
        public tblStyleMaster()
        {
            this.tblFavorites = new HashSet<tblFavorite>();
            this.tblInventories = new HashSet<tblInventory>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<short> VendorId { get; set; }
        public string VendorStyle { get; set; }
        public string StoreStyle { get; set; }
        public Nullable<short> ClassId { get; set; }
        public string ShortDescr { get; set; }
        public Nullable<short> SizeRangeId { get; set; }
        public Nullable<short> ExtraSizeRangeId1 { get; set; }
        public Nullable<decimal> Charge1 { get; set; }
        public Nullable<short> ExtraSizeRangeId2 { get; set; }
        public Nullable<decimal> Charge2 { get; set; }
        public Nullable<decimal> XLCharge { get; set; }
        public Nullable<short> NeckLineId { get; set; }
        public Nullable<short> SilhouetteId { get; set; }
        public Nullable<short> FabricId { get; set; }
        public Nullable<short> SleeveId { get; set; }
        public bool IsServiceItem { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> CommissionPrice { get; set; }
        public Nullable<double> CommissionPercent { get; set; }
        public bool IsTax1 { get; set; }
        public bool IsTax2 { get; set; }
        public string LongDescr { get; set; }
        public bool IsReorderable { get; set; }
        public Nullable<System.DateTime> DiscDate { get; set; }
        public Nullable<short> RegLeadTime { get; set; }
        public Nullable<short> RushLeadTime { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblFabric tblFabric { get; set; }
        public virtual ICollection<tblFavorite> tblFavorites { get; set; }
        public virtual ICollection<tblInventory> tblInventories { get; set; }
        public virtual tblNeckLine tblNeckLine { get; set; }
        public virtual tblSilhouette tblSilhouette { get; set; }
        public virtual tblSizeRange tblSizeRange { get; set; }
        public virtual tblSizeRange tblSizeRange1 { get; set; }
        public virtual tblSizeRange tblSizeRange2 { get; set; }
        public virtual tblSleeve tblSleeve { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
