//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityLevel
    {
        public tblSecurityLevel()
        {
            this.tblGeneralReports = new HashSet<tblGeneralReport>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblGeneralReport> tblGeneralReports { get; set; }
    }
}
