//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicketDetail
    {
        public tblTicketDetail()
        {
            this.tblCommissions = new HashSet<tblCommission>();
            this.tblPurchaseOrderDetails = new HashSet<tblPurchaseOrderDetail>();
        }
    
        public int Id { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public short TransactionTypeId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<short> ColorId { get; set; }
        public string Size { get; set; }
        public string XL { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public decimal RunningTotal { get; set; }
        public Nullable<decimal> ChangeDue { get; set; }
        public string VendorNote { get; set; }
        public string StoreNote { get; set; }
        public Nullable<short> ConsultantId1 { get; set; }
        public Nullable<short> ConsultantId2 { get; set; }
        public Nullable<short> ConsultantId3 { get; set; }
        public Nullable<short> StatusId { get; set; }
        public Nullable<short> PaymentTypeId { get; set; }
        public string CreditNumber { get; set; }
        public string PaymentRef { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<short> RefundTypeId { get; set; }
        public bool IsStoreCredit { get; set; }
        public string StoreCheck { get; set; }
        public string StoreCheckRef { get; set; }
        public string RefundRef { get; set; }
        public Nullable<bool> IsUpdatedReceiptId { get; set; }
    
        public virtual ICollection<tblCommission> tblCommissions { get; set; }
        public virtual ICollection<tblPurchaseOrderDetail> tblPurchaseOrderDetails { get; set; }
    }
}
