//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridalPOS.Model.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public tblVendor()
        {
            this.tblLeadTimes = new HashSet<tblLeadTime>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblStyleMasters = new HashSet<tblStyleMaster>();
        }
    
        public short Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Contact { get; set; }
        public string Manager { get; set; }
        public string ARContact { get; set; }
        public string Acc { get; set; }
    
        public virtual ICollection<tblLeadTime> tblLeadTimes { get; set; }
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        public virtual ICollection<tblStyleMaster> tblStyleMasters { get; set; }
    }
}
